[package]
name = "mt"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
rpassword = "7.3.1"
thiserror = "2.0.12"

[[bin]]
name = "mt"
path = "main.rs"
