[package]
name = "mt"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
dirs = "6.0.0"
rpassword = "7.3.1"
serde = { version ="1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"

[[bin]]
name = "mt"
path = "main.rs"
